### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by kylesloan** [ns1/ns1-ansible-modules#10]
Not seeing many commits and the readme seems to have many TODOs in it.

**Comment by mburtless** [comment]
Hi @kylesloan, thanks for checking in on the project and apologies for the delayed response.

I've just joined NS1 and will be maintaining the repo moving forward, so I can confirm that it is alive and the remaining TODOs should see movement soon.

I'm going to close out this issue, but feel free to open new issues as they come up so we can address them.
