### ISSUE TITLE
Migrate away from deprecated nsone

### ISSUE THREAD

**Issue by ignatenkobrain** [ns1/ns1-ansible-modules#15]
Is there reason why this repo uses obsolete `nsone` python module? Or this repo is just unmaintained?

**Comment by mburtless** [comment]
The Ansible modules in this repo already migrated from the deprecated `nsone` python SDK to `ns1` SDK in PR #9.  However, looks like README wasn't updated accordingly, which we can get fixed soon.

Is there another dependency on the obsolete python module that you're referring to that should also be migrated?

**Comment by ignatenkobrain** [comment]
Also:

* https://github.com/ns1/ns1-ansible-modules/blob/master/library/ns1_record#L30
* https://github.com/ns1/ns1-ansible-modules/blob/master/library/ns1_zone#L30

**Comment by ignatenkobrain** [comment]
> Is there another dependency on the obsolete python module that you're referring to that should also be migrated?

no, just what you mentioned.

**Comment by mburtless** [comment]
👍 Thanks for the heads up, I'll get those updated today
