### ISSUE TITLE
RFC: Move modules to the ansible repo

### ISSUE THREAD

**Issue by ignatenkobrain** [ns1/ns1-ansible-modules#16]
Is there reason that these modules are not in the ansible repo? https://github.com/ansible/ansible/tree/devel/lib/ansible/modules

I think it would be beneficial for everyone to have them there since ansible community would give feedback on modules themselves and also make available for all users without having to use separate repos.

**Comment by mburtless** [comment]
This is already a work in progress.  Here's the initial PR that would migrate the ns1_record module and create the ns1 namespace within the Ansible project: https://github.com/ansible/ansible/pull/53964.

Unfortunately, the PR has been languishing for sometime.  Once this has been merged, we can continue to submit other ns1 modules to the core Ansible project.

**Comment by mburtless** [comment]
Closing this issue out as this now appears unlikely to happen.

Ansible is moving away from adding modules directly to core and encouraging folks to distribute via Collections.  Adding support for distributing our modules via collections has been added to our backlog.
