### ISSUE TITLE
Bug when adding already existed record 

### ISSUE THREAD

**Issue by haklj** [ns1/ns1-ansible-modules#20]
Hi, I'm getting the error below when trying to add already existed record.

`
fatal: [ctl-bastion02a.int.na3.pcigdc.com -> localhost]: FAILED! => {"changed": false, "module_stderr": "/home/honza/.ansible/tmp/ansible-tmp-1564495570.2179096-168719357499967/AnsiballZ_ns1_record:18: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses\n  import imp\nTraceback (most recent call last):\n  File \"/home/honza/.ansible/tmp/ansible-tmp-1564495570.2179096-168719357499967/AnsiballZ_ns1_record\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/honza/.ansible/tmp/ansible-tmp-1564495570.2179096-168719357499967/AnsiballZ_ns1_record\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/honza/.ansible/tmp/ansible-tmp-1564495570.2179096-168719357499967/AnsiballZ_ns1_record\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib64/python3.7/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib64/python3.7/imp.py\", line 169, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n  File \"/tmp/ansible_ns1_record_payload_8uk7rrf3/__main__.py\", line 389, in <module>\n  File \"/tmp/ansible_ns1_record_payload_8uk7rrf3/__main__.py\", line 359, in main\n  File \"/tmp/ansible_ns1_record_payload_8uk7rrf3/__main__.py\", line 274, in update\n  File \"/tmp/ansible_ns1_record_payload_8uk7rrf3/__main__.py\", line 228, in clean\n  File \"/tmp/ansible_ns1_record_payload_8uk7rrf3/__main__.py\", line 234, in clean\n  File \"/tmp/ansible_ns1_record_payload_8uk7rrf3/__main__.py\", line 226, in clean\nRuntimeError: dictionary changed size during iteration\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
`

and this is code what I'm using to run:
```
---
- name: Add DNS entries to NS1
  hosts:
    - all
  gather_facts: no
  tasks:
    - ns1_record:
            apiKey: xxxxxx
            name: "{{ inventory_hostname_short }}"
            zone: kkt.pcigdc.com
            state: present
            type: A
            answers:
              - answer:
                - "{{ dns.ext }}"
                meta:
                  up: True
            ttl: 360
      delegate_to: localhost
      register: kkt
    - debug: msg={{ kkt }}
```

**Comment by mburtless** [comment]
Hi @haklj - This is a known bug in the current version of the module on this repo.  However, this has already been resolved in the next version of the module, which we are preparing to release in this repo and on galaxy shortly.  We have also submitted this for inclusion in ansible-core.

For the time being the newest version can be found at https://github.com/ns1/ns1-ansible-modules/tree/v2.  To use this module, please clone this branch directly or install via galaxy:
```
ansible-galaxy install git+https://github.com/ns1/ns1-ansible-modules.git,v2
```
Note that if you install via galaxy in this way, you'll need to import the role in your playbook by adding a task like:
```
- import_role:
     name: ns1-ansible-modules
```

I'll close this issue out once the `v2` branch has been merged and the updated module is able to be installed via galaxy natively without referencing git.

**Comment by mburtless** [comment]
@haklj - While the info above is still true, I'm realizing this bug should already have been resolved in the current version of the module in #8.

Have you updated your local version of the module recently?  I'm unable to recreate using a similar playbook with the current version of the role.

**Comment by mburtless** [comment]
Closing this out as v2 has been merged to master.  Please install the latest version of the role (`ansible-galaxy install ns1.ns1`) and open a new issue if you encounter this issue again.
