### ISSUE TITLE
Ansible 2.x support

### ISSUE THREAD

**Issue by listx** [ns1/ns1-ansible-modules#4]
I realize that this was released just a few weeks ago, but my company cannot use it because we're running on Ansible 2.1.

What's the timeline for supporting Ansible 2.x?

**Comment by CheRuisiBesares** [comment]
More ns1 api coverage and getting this up to date with 2.0 best practices is on our upcoming roadmap. Unfortunately I don't have exact dates at this time. I think that the fixes I just pushed up should allow existing modules to work in 2.0. Please let me know if you find anything else that looks off. Thanks for your time sorry for the delay getting back to you.

**Comment by mbubb** [comment]
ah _ i didnt realize this does not work for 2.0 you should put this on the README and in Galaxy

**Comment by mstyne** [comment]
I would love to see this role updated for a more contemporary version of Ansible. Thanks guys!

**Comment by mstyne** [comment]
Some further testing seems to indicate all is well with ansible 2.3.1.0, sorry for the false alarm!

**Comment by mburtless** [comment]
I've just joined the team at NS1 and will be helping to maintain this project moving forward.

I've successfully ran the test.yml playbook from this repo using the latest release of Ansible (2.7.15).  In the interest of cleaning up old issues, I'm going to close this out.

If you are still experiencing any issues using this module with the latest version of Ansible, please open a new issue with relevant details.  Thanks!

**Comment by mstyne** [comment]
Welcome aboard, @mburtless !

**Comment by mburtless** [comment]
Thanks, @mstyne Looking forward to helping out here!
